# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.41.2"

package:
  name: opendal-oli
  version: ${{ version }}

source:
  url: https://crates.io/api/v1/crates/oli/${{ version }}/download
  sha256: 5d4247a38af59d6429b39fa97b535267b3705781ea877af106439ed54f4973b0

build:
  script:
    interpreter: nu
    content: |
      # Build oli from crates.io source
      cd oli-${{ version }}
      ^cargo install --locked --bins --root ($env.PREFIX) --path .
      mkdir ($env.PREFIX)/share/oli
      ^cargo-bundle-licenses --format yaml --output ($env.PREFIX)/share/oli/THIRDPARTY.yml

requirements:
  build:
    - nushell
    - tar
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  # Test 1: Verify package contents are included
  - package_contents:
      files:
        # OpenDAL oli binary
        - ${{ "Library/" if win }}bin/oli${{ ".exe" if win }}

      # Test 2: Functional test
  - requirements:
      build:
        - nushell
    script:
      interpreter: nu
      content:
        - ^oli --help # !(2)

about:
  homepage: https://opendal.apache.org/apps/oli/
  license: Apache-2.0
  license_file:
    - "LICENSE"
    - "*/share/oli/THIRDPARTY.yml"
  summary: Apache OpenDAL™ Oli
  description: |
    oli stands for OpenDAL Command Line Interface
    oli aims to provide a unified and user-friendly way
    to manipulate data stored in various storage service.
  repository: https://github.com/apache/opendal/tree/main/bin/oli

extra:
  recipe-maintainers:
    - phreed
  version:
    github-tags:
      - ^(\d+\.\d+\.\d+)
